/** the icon language lives in @arivo/ui (one family, one stroke — gate 1).
 *  these shims keep the existing call sites; a new glyph goes upstream,
 *  never here. */
export {
  Icon,
  IconSearch,
  IconPlus,
  IconGrid,
  IconList,
  IconBook,
  IconSun,
  IconMoon,
  IconLamp,
  IconType,
  IconToc,
  IconNote,
  IconBookmark,
  IconX,
  IconBack,
  IconTrash,
  IconDownload,
  IconCollection,
  IconCheck,
  IconChevronRight,
  IconDots,
  IconZoomIn,
  IconZoomOut,
  IconFitWidth,
  IconFitPage,
  IconShelf,
  IconArchive,
  IconSettings,
  IconInfo,
  IconTag,
  IconPencil,
  IconFolder,
  IconPulse,
} from '@arivo/ui';
